// <auto-generated />
namespace BOMB.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AccountPrivateGuid : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207170258078_AccountPrivateGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soydffvFk/DRrs4/S47LICIHXeXn+ntjsPAQ2H9l+qKdTwqi9fnO9yrm3zz46nk4rQtNvRM1+r/w6+IA+ellXq7xur1/l5/rq2eyj9G743t3ui/Y17x30Tr8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t2csVcqPFp9ejtCPLy7swdC3M2Wy6rNWprbHuIdNF+uJ2Ux/XxdWHTl9x62N4Cpi0sawgfDOSkz4qOZEOC8yGsD7XVbEwt/lD4r3uWz5/nyop1bkF9k78wnuzs7xMlfLQtieXqrrdf5e+NwusiK8ng2q/Omec/u9+5/cO9Pi2ZVZtf44z07333foT++64SkLzokxG1WEGsqYk+qxQSf5e+6MiTtX+dtKGlEPAdfxHpshDCKh+3R6Yu7ojCMYrk7oFkef5GtVkQjT9PoJ+lrUTMn26/fX6csBMbdaRNRLRZb2xMJc3aRd76lrgnTZ0XdtNBykwyzcDJb9Jrdgr6mpw6ZuwrMUd28gN91Fo26tVPReduR7hmNZkFyyAPTYRESA5pU3309zcqsjujCk6pcL5ZD+nTT276K8qH4n78HNF9TBeD8L24PL6KxfKiRr28PO9REPtjwm9tDDLSLDzD4og/v8d0OU3R5zlMl2rJjL7tMvEn+u01s71YPdOT9screze5GTxilyUcpEeqymEEQX183bb4QIXn9i8qTssihsUyDL7JlcZ437ZvqbQ7XiXTF13ddrMVumln5/1L/pcDob/RU3tPM9f2O9bL4Reu88ATlfUH2fZAPhjnojywvs3o6z+qI9/GeXcTcjSh0di7eE3jEmxjC/Bt1Fvo2b8CkdZh7g8cggvrZR7NJRUMRPD/Uneirjcd3/Vjm8dO8KS4cCEQ2y3wKx9oBNW3OlueVIT+NzMfINOnMzhd5m82IQMc1MVc2benrKXEBO3s/mZVr5o4Jsd/yy3W7WrfHTZMvJuW1P97Hdzf3zz5TiPPjL1f4y9OTX38IhGZBQ8i/XD5ZF+XM4v0swkEDIMArqlkIK3J2CdzFtYX0olreEpCS72m+ypcQ2Df5gpi/zZsvl6+zy3wYt5tpGFLs8dMiu6izhU9B+UQxeZ1Rz14X1IH/huuP/iR2pUD66P8JAAD//wQFgcC9DwAA"; }
        }
    }
}
