// <auto-generated />
namespace BOMB.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Account : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207120440273_Account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soydffvFk/DRrs4/S47LICIHXeXn+ntjsPAQ2H9l+qKdTwqi9fnO9yrm3zz46nk4rQtNvRM1+r/w6+IA+ellXq7xur1/l5/rq2eyj9G743t3ui/Y17x30Tr8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t2csVcqPFp9ejtCPLy7swdC3M2Wy6rNWprbHuIdNF+uJ2Ux/XxdWHTl9x62m8GclBnN/0wQPy/y2kB73dbEeh+lz4p3+ex5vrxo5xbkF9k788nuzg5x4FfLgliV3mrrdf7eOJwusqI8ns3qvGnes/u9+x/c+9OiWZXZNf54z85333foj+865u6zPAlfmxXEUorYk2oxwWf5uy7vS/vXeRtKCBHPwRdxHBvhieJhe3RyflcE3SiEuwMa4fEX2WpFNPI0hH6Svhb1cLL9+v11wUJg3J02EZVgsbU9kRBmF3nnW+qaMH1W1E0L7TTJMAsns0Wv2S3oa3rqkLmreBzVzQv4XWfRqEk7FZ23Heme0WgWJIc8MB0WITGgAfXd19OszOqIDjupyvViOaQHN73tqxYfiv/57aFFNIwPNPL17WGHmsMHG35ze4iBNvABBl/04T2+25nELo94oq8tO3apy3Sb5LXbxPZu5bYjn49VVm426z3hkSYfpUSoy2IGwXl93bT5Qpj69S8qT8oih4YxDb7IlsV53rRvqrc5XBSS7a/vIljL2DSz8v+lfkKB0d/oEbynWerb9/Wy+EXrvPAE5T1BDtr65WVWT+dZHbHs79lFzJRHobPhfk/gEUs9hPk3aoj79mTAXHQYcYM1FqH67KPZpKKhCJ4faqr7Iv74ru/fP36aN8WFAwFvf5lP4Ww6oKbN2fK8MuSnkfkYmSad2fkib7MZEei4JubKpi19PSUuYEfqJ7NyzdwxIfZbfrluV+v2uGnyxaS89sf7+O7m/tkfCXF+/OUKf3k67esPgdAsaAj5l8sn66KcWbyfRThoAAR4RbUAYUWOJIG7uLaQXlTLWwJS8j3NV/kSAvsmXxDzt3nz5fJ1dpkP43YzDUOKPX5aZBd1tvApKJ8oJq8z6tnrgjrw33D90Z/ErhRcHv0/AQAA//9Kkd6j0Q4AAA=="; }
        }
    }
}
