// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BOMB.Web.Controllers {
    public partial class AccountController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LogOnStep2() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LogOnStep2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LogOff() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LogOff);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string LogOn = "LogOn";
            public readonly string LogOnStep2 = "LogOnStep2";
            public readonly string FirstTimeLoggingIn = "FirstTimeLoggingIn";
            public readonly string LogOff = "LogOff";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string LogOn = "LogOn";
            public const string LogOnStep2 = "LogOnStep2";
            public const string FirstTimeLoggingIn = "FirstTimeLoggingIn";
            public const string LogOff = "LogOff";
        }


        static readonly ActionParamsClass_LogOnStep2 s_params_LogOnStep2 = new ActionParamsClass_LogOnStep2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogOnStep2 LogOnStep2Params { get { return s_params_LogOnStep2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogOnStep2 {
            public readonly string userToken = "userToken";
            public readonly string emailAddress = "emailAddress";
        }
        static readonly ActionParamsClass_LogOff s_params_LogOff = new ActionParamsClass_LogOff();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogOff LogOffParams { get { return s_params_LogOff; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogOff {
            public readonly string redirectTo = "redirectTo";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string FirstTimeLoggingIn = "~/Views/Account/FirstTimeLoggingIn.cshtml";
            public readonly string LogOn = "~/Views/Account/LogOn.cshtml";
            public readonly string LogOnStep2 = "~/Views/Account/LogOnStep2.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AccountController: BOMB.Web.Controllers.AccountController {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult LogOn() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOn(string openid_identifier) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openid_identifier", openid_identifier);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOnStep2(System.Guid userToken, string emailAddress) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOnStep2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userToken", userToken);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "emailAddress", emailAddress);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOnStep2(BOMB.Web.ViewModels.Account.Step2 model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOnStep2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult FirstTimeLoggingIn() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.FirstTimeLoggingIn);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOff(string redirectTo) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOff);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "redirectTo", redirectTo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
